project:
  type: website

website:
  title: "Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 0_data_preprocessing.qmd
      - 1_sanity_check_qc.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



